# Specify the list of keys you want to send over MQTT

mqtt_broker_address: 'nas.ds18' # Set this to your mqtt broker address
mqtt_username: 'mqtt_user' # Uncomment and change this to your username if required
mqtt_password: 'xyzxyz'

# List the (OBIS) values that you want to send to the mqtt broker
values_of_interest:
  - CURRENT_ELECTRICITY_DELIVERY
  - ELECTRICITY_EXPORTED_TOTAL
  - CURRENT_PANEL_POWER
  - CURRENT_PANEL_VOLTAGE
  - CURRENT_PANEL_CURRENT
  - SG_SERIAL

client: serial
serial_device: /dev/ttyS0

topic: DS18/PV/StecaGrid_3600

